### ISSUE TITLE
Compose version

### ISSUE THREAD

**Issue by tsviet** [aerokube/selenoid-grafana-example#1]
root@psapidevlinux:/home/mark/selenoid-grafana-example# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by lanwen** [comment]
just update your docker-compose
